### PR TITLE
hotfix for no constraints case

### PR DESCRIPTION
**Pull request by vsamy**
Hi,

This a fix in case where no equality constraints or inequality constraints are made.
In that case the Eigen matrix Aeq and Aineq are 0-by-nrvars_ matrices.

### CODE REVIEW

**Comment by haudren** [comment]
Hi,
Thanks for the report. I won't merge in this form as:
- Indentation is not respected
- You removed braces around single statement ifs and fors (This is more of a personal taste)

Anyway, I would like to slightly rework that part of the code, I'll fix this tomorrow.

**Comment by vsamy** [comment]
OK thanks

**Comment by vsamy** [comment]
Anyway, if needed, i have updated my branch with good indentations and brackets.

**Comment by haudren** [comment]
Ok thanks, I'll merge and implement my solution :smile_cat:

**Comment by haudren** [comment]
I moved all the constraints updates in a separate function, `updateConstr` to avoid code duplication. I initially wanted to get rid of the `if`s and do a single loop over the number of constraints, but this would have required changing the storage order of each and every matrix to row storage, thus copying them around.

**Pull request merged**
